spring:
  data:
    mongodb:
      username: rares
      password: rares
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

springdoc:
  api-docs:
    path: /api/v1/customers/v3/api-docs

server:
  forward-headers-strategy: framework
  port: 8090